name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD VUE🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 10.8.2
          cache: "npm"
      - run: cd web2
      - run: npm install
      - run: npm run build --if-present
      - run: ls -la dist || echo "⚠️ Directori 'dist' no existeix!"
      - uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist

  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      # 👇 Descargar el artifact del build
      - name: Descarregant l'arxiu construït
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist

      - name: Verificar contenid del directori descarregat
        run: ls -la dist || echo "⚠️ No s'ha descarregat res a 'dist'!"

      - name: scp a produccio
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./web2/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/a22jhepincre/web/a22jhepincre.daw.inspedralbes.cat/public_html/ghactions-a22jhepincre/vue

      - run: echo "🍏 This job's status is ${{ job.status }}."
